defaults:
    -
        scope:
            path: "de"
        values:
            layout: "default"
            lang: "de"
            language: "german"
            versiontitle: "Davids persönliche Website"
    -
        scope:
            path: "en"
        values:
            layout: "default"
            lang: "en"
            language: "english"
            versiontitle: "David's personal website"
    -
        scope:
            path: "es"
        values:
            layout: "default"
            lang: "es"
            language: "spanish"
            versiontitle: "Sitio web de David"

# Build settings
compress_html:
    clippings: all
    comments: all
sass:
    style: compressed

exclude: [
    "CNAME",
    "TODO.md"
]
